# -*- coding: utf-8 -*-
"""Copy of Reduction_strategies_for_CIFAR10_ClassIncremental_SR1_experiments.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B0Zyh6_gUoVytfH1IpDGHbE0JrKNQCDr

# CIFAR-100 Class-Incremental Experiments with S-LSR1

Tasks: Ten CIFAR-100 tasks, each with 10 of the 100 classes. Each task has a separate classification layer.

Model: 2 conv layers + 2 linear layers, 62k parameters in total.
"""

import torch
from dataset import *
import model
import argparse
from train_functions import *
import logging
from csqn import CSQN
from dataset import *

FORMAT = '%(asctime)-15s %(message)s'
logging.basicConfig(format=FORMAT, level=logging.DEBUG, datefmt='%m/%d/%Y %I:%M:%S %p')
logger = logging.getLogger('main')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
logger.debug('Device is: %s', device)


parser = argparse.ArgumentParser(description='Split CIFAR-100 Baselines..')
parser.add_argument('--method', type=str, default="SR1", help='BFGS or SR1')
parser.add_argument('--m', type=int, default=10, help='Number of components')
parser.add_argument('--start', type=int, default=1, help='ID of first iteration')
parser.add_argument('--iter', type=int, default=5, help='Number of iterations')
parser.add_argument('--reduction', type=str, default='none', help='How to reduce Z')
parser.add_argument('--tasks', type=int, default=10, help='Number of tasks to run')

args = parser.parse_args()

""" SQN Settings """
M, method = args.m, args.method  # 'SR1' or 'BFGS'
start_id, iterations = args.start, args.iter
consolidation = 'Z'  # 'Z' or 'XA'
reduction = args.reduction  # 'none', 'auto', 'split', 'tree' - only relevant if consolidation = 'Z'
eps_ewc = 1e-2
init_alpha = 100000 // M

""" Hyper-parameter search settings """
p_hyp = 0.8  # method must at least reach p*ACC_FT on new task
a_hyp = 0.5  # decaying factor

""" Experimental settings """
n_epoch = 5
n_tasks = args.tasks
batch_size = 64
res_name = 'cifar100_results_%d' % n_tasks
first_task = 'task1_cifar100_%d' % (100 // n_tasks)

""" Loading the data"""
train_data, dev_data, test_data, n_classes = get_split_cifar100_data(n_tasks, batch_size)

Net = lambda: model.get_net('lenet', [n_classes] * n_tasks)
net, shared_layers = model.get_net('lenet', [n_classes] * n_tasks, return_shared_layers=True)

logger.debug("Neural network contains " + str(torch.cat([p.view(-1) for p in list(net.parameters())]).numel())
             + " parameters.")
for n, p in net.named_parameters():
    logger.debug(n + ' contains %d parameters' % (p.numel()))


try:
    results = torch.load(res_name, map_location=device)
except Exception as e:
    logger.warning('Exception occured: %s - could not load results file %s' % (str(e), res_name))
    results = {}

init(train_data, dev_data, test_data, res_name, n_tasks, n_epoch, n_classes, shared_layers)

net_one = Net()
net_one.load_state_dict(torch.load(first_task))


logger.info("")
logger.info("# 3 Experiments with CL with SQN Regularization")


for num in range(start_id, start_id + iterations):

    mod_list = [copy.deepcopy(net_one).state_dict()]

    logger.info("### RUN %d of %d " % (num, iterations))
    c_sqn = CSQN(method=method, shared_layers=shared_layers, M=M, eps_ewc=eps_ewc, reduction=reduction,
                 n_classes=n_classes)

    for task in range(n_tasks - 1):

        logger.info("Adapting Task %d to Task %d" % (task, task + 1))
        net_ = Net()
        net_.load_state_dict(mod_list[-1])
        names, accs = [('Task %d' % i) for i in range(task + 1)], [round(test(net_, i, 'dev', print_result=False), 2)
                                                                   for i in range(task + 1)]
        logger.info('Initial model: ' + str(names) + " = " + str(accs))

        c_sqn.update(copy.deepcopy(net_), train_data(task), task)

        logging.debug("Adapting without regularization..")
        train_net(net_, task + 1, epochs=n_epoch)
        acc_ft = test(net_, task + 1, 'dev')

        acc, alpha = 0, init_alpha

        while acc < p_hyp * acc_ft:
            logger.info(c_sqn.get_name() + '-T%d [%d]' % (task, alpha))
            net_ = Net()
            net_.load_state_dict(mod_list[-1])
            train_net(net_, task + 1, reg_loss=lambda x: c_sqn.regularize(x, alpha), epochs=n_epoch)
            acc = test(net_, task + 1, 'dev')
            logger.info("[Task %d] = [%.2f]" % (task + 1, acc))
            alpha = a_hyp * alpha

        best_alpha = alpha / a_hyp
        logger.info("Best alpha was %d - with an average accuracy of %.2f" % (best_alpha, acc))

        mod_list.append(net_.state_dict())

    logger.info("## 3.3 Evaluation")
    logger.info(c_sqn.get_name())
    net_list = []
    for mod in mod_list:
        net_ = Net().cpu()
        net_.load_state_dict(mod)
        net_list.append(net_)
    test_and_update(net_list, c_sqn.get_name() + ' %d' % num)

